apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernets-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernets
  template:
    metadata:
      labels:
        app: kubernets
    spec:
      containers:
        - name: kubernets
          image: okanumur/kubernets-jenkins:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kubernets-service
spec:
  type: NodePort
  selector:
    app: kubernets
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30036
